### PR TITLE
Add Ristretto255 Support

### LINKED ISSUE #45: Finite Field Artithmetic not implemented?
I haven't been able to find functions relating to libsodiums [Finite Field arithmetic](https://doc.libsodium.org/advanced/point-arithmetic#scalar-multiplication). If they're available how do I invoke them? Thanks.

### PR DESCRIPTION
**Pull request by Traderjoe95**
This PR adds support for Libsodium's [Finite Field Arithmetic](https://doc.libsodium.org/advanced/point-arithmetic) API.

Closes #45

### CODE REVIEW

**Comment by Traderjoe95** [comment]
@ionspin, at this point I only added Ristretto255 support. Please have a look at the API. It is slightly different from the others: I added two classes (`Ristretto255.Point`, `Ristretto255.Scalar`) to support some syntactic sugar (like Kotlin operators) on Ristretto255 points and scalars. The raw bytes API is provided in addition by an abstract base class.

Please tell me if you'd like to keep it like this or if you only want the low-level APIs.

**Comment by ionspin** [comment]
Hey @Traderjoe95, thank you very much for the effort, I'll have a look over the weekend, or sooner if I get some free time.

**Comment by Traderjoe95** [comment]
Ed25519 Finite Field arithmetic was added. For some reason, I can't run the native build on my machine (Windows 11) - it always complains about missing `sodium.h`, although I checked out the submodule. Any idea what I might be missing?

**Comment by ionspin** [comment]
Hey @Traderjoe95, try initializing and updating git submodules, since that is how we import libsodium. I'm not using Windows 11 for development, so I'm not completely sure that's going to solve your problems, but it's worth a try if you didn't do it before.

**Comment by Traderjoe95** [comment]
Okay, right now I am running builds in WSL, which is working fine so far. Build for JVM/Linux Native/JS is running fine now.

**Comment by ionspin** [comment]
Let me look into this last failure, I think I might have a clue on what is going on, probably need to update the dylib in JVM resource folder.

**Comment by ionspin** [comment]
@Traderjoe95 With the updated lib all the checks are passing :tada: I'll go through the pull request in more detail over the weekend.

Just one request, before I get to reviewing, your IDE seems to be set to 2 space indents, and the rest of the project is on 4. Could you please reformat the files to 4? Especially the `JnaLibsodiumInterface.kt` that seems to have 2430 lines changed, and I think a large part of it is reformatting from 4 spaces to 2 spaces.

Thanks for all the work you put into this pull request!

**Comment by Traderjoe95** [comment]
> Just one request, before I get to reviewing, your IDE seems to be set to 2 space indents, and the rest of the project is on 4. Could you please reformat the files to 4? Especially the JnaLibsodiumInterface.kt that seems to have 2430 lines changed, and I think a large part of it is reformatting from 4 spaces to 2 spaces.

Sure, that change was unintentional. I reverted all of that. Additionally, I added an `.editorconfig` file setting the indent size for Kotlin files in the whole project. It should be picked up automatically by all major IDEs 😄

**Comment by Traderjoe95** [comment]
And, by the way, I will of course add all necessary KDoc documentation once the API is final

**Comment by ionspin** [comment]
Hey @Traderjoe95, I've had some time to look over the pull request, and I think it's great work, I really like that you made the kotlin idiomatic higher level API but I do have some questions and suggestions regarding it. I've never used libsodium finite field arithmetic directly so feel free to correct me if I'm missing a point of a part of the API. 

With that said, let's get to the actual points:

### Ed25519LowLevel and Ristretto25519LowLevel being abstract classes
https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/2887ae253514b59a04ef34eb161c7c6caf636f99/multiplatform-crypto-libsodium-bindings/src/commonMain/kotlin/com.ionspin.kotlin.crypto/ed25519/Ed25519.kt#L19-L21

I don't quite understand why are they abstract classes, as I wouldn't expect to have multiple instances of `...LowLevel` since there is no internal state to track. 

My suggestion here would be to follow the rest of the library and make this an `expect object`

I understand that they are used by the higher level API to inherit but I don't think we would want that and that's the next point that I would like to address.



### Ed25519 and Ristretto25519 expose both high level and low level APIs
https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/2887ae253514b59a04ef34eb161c7c6caf636f99/multiplatform-crypto-libsodium-bindings/src/commonMain/kotlin/com.ionspin.kotlin.crypto/ed25519/Ed25519.kt#L39-L43

I think this would make it a bit confusing, i.e. if you wanted to add two points using Ed25519 you would have 3 options to do that :
  ```kotlin
Ed25519.addPoints(p: UByteArray, q: UByteArray): UByteArray
Ed25519.addPoints(p: Point, q: Point): Point
operator fun Ed25519.Point.plus(q: Potin): Point
```

If we apply the previos suggestion and make the `...LowLevel`  a `object` we could define a `lowLevel` member and then use that to invoke the actual low level functions

i.e.
```kotlin
object Ed25519 {
    private val lowLevel = Ed25519LowLevel()
    fun add(p: Point, q: Point): Point =
        Point(lowLevel.addPoints(p.encoded, q.encoded))

    fun subtract(p: Point, q: Point): Point =
        Point(lowLevel.subtractPoints(p.encoded, q.encoded))
   etc.
```

Which brings me to my last point
### Ed25519/Ristretto25519 is a very thin wrapper around (Ed25519/Ristretto25519)LowLevel 

This is really a point of API styling, but instead of providing two different approaches with the thin wrapper in Ed25519/Ristretto25519 i.e.:
https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/2887ae253514b59a04ef34eb161c7c6caf636f99/multiplatform-crypto-libsodium-bindings/src/commonMain/kotlin/com.ionspin.kotlin.crypto/ed25519/Ed25519.kt#L41-L43

and other option in higher level Point:
https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/2887ae253514b59a04ef34eb161c7c6caf636f99/multiplatform-crypto-libsodium-bindings/src/commonMain/kotlin/com.ionspin.kotlin.crypto/ed25519/Ed25519.kt#L86-L87

I would just directly offer only the higher level Point and move the implementation there, i.e.:
```kotlin
    data class Point(private val encoded: UByteArray) {
        operator fun plus(q: Point): Point = Point(lowLevel.addPoints(this.encoded, q.encoded))
```
(while also making the UByteArray private as well)

---------------

That is pretty much it regarding the API, I think with these changes proposed we get a simpler API with cleaner separation between low and high level options. 

Once again thanks for all the great work so far, it's really appreciated!

**Comment by ionspin** [comment]
@Traderjoe95 If you don't have time to work on this I could jump in and make these changes, just let me know!

**Comment by ionspin** [comment]
@Traderjoe95 I went ahead and implemented the changes, if you'd like to check if I missed anything that would be great!

**Comment by Traderjoe95** [comment]
Hi, sorry for basically disappearing over the last two weeks. First week I got carried away at work and then I got hit by a car while riding the bike. I luckily got away with relatively mild injuries, especially considering the heavy impact, but still had to spend a few days in the hospital and did not have much time and opportunity to do anything at all since then. But it looks like I might be able to have a look these coming days. Thanks for your work implementing the suggestions.Am 01.09.2024 16:51 schrieb Ugljesa Jovanovic ***@***.***>:
@Traderjoe95 I went ahead and implemented the changes, if you'd like to check if I missed anything that would be great!

**Comment by ionspin** [comment]
Oh wow, I'm sorry to hear that, I wish you speedy recovery! Take your time and heal well, there is no rush to get this merged!

**Comment by ionspin** [comment]
Hey @Traderjoe95 I hope you are well! I'll try to spend some time over the weekend and get this merged, so if you want to give it a look before that, that would be great!

**Comment by Traderjoe95** [comment]
HI @ionspin, sorry, I completely forgot about this. I think I even looked at your changes once but then got sidetracked and forgot again 😁 

I will quickly look at it again. If I remember correctly, there were one or two things that I thought could be slightly refactored, so I will give it another try

**Comment by ionspin** [comment]
> Made val encoded: UByteArray public again. This is the one thing I'm not quite sure about. I think the user should be able to access the raw encoding of a point or scalar, be it to call the low-level API (not really needed, the high level API has full coverage), or to pass it to some external component or service or whatever. But then again, UByteArrays are mutable, so it would enable anybody with access to the object to change the internal value. I like to forbid any unintended usage in an API, so I don't like this possibility. A possible solution would be to make it private and offer a public property that simply returns a copy. What do you think?

I think it's fine the way you did it, I consider this library to be "sharp edges included", I also have another higher level library that wraps this one and that takes care of these "sharp edges", but I haven't published it anywhere yet.

> Anyway, just tell me what you think, I'm happy to have this merged soon 👍

Awesome work, I highly appreciate all the effort and the time you put into this! Thank you for the contribution and I hope you keep contributing in the future!

**Pull request merged**
